// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VaxWise.API.Data;

#nullable disable

namespace VaxWise.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504125701_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VaxWise.API.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnimalId"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComplianceScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CurrentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EarTagNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RfidTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimalId");

                    b.HasIndex("AnimalTypeId");

                    b.HasIndex("FarmId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("VaxWise.API.Models.AnimalType", b =>
                {
                    b.Property<int>("AnimalTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnimalTypeId"));

                    b.Property<int>("GestationDays")
                        .HasColumnType("integer");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnimalTypeId");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            AnimalTypeId = 1,
                            GestationDays = 283,
                            TypeName = "Cattle"
                        },
                        new
                        {
                            AnimalTypeId = 2,
                            GestationDays = 147,
                            TypeName = "Sheep"
                        },
                        new
                        {
                            AnimalTypeId = 3,
                            GestationDays = 150,
                            TypeName = "Goat"
                        },
                        new
                        {
                            AnimalTypeId = 4,
                            GestationDays = 114,
                            TypeName = "Pig"
                        },
                        new
                        {
                            AnimalTypeId = 5,
                            GestationDays = 21,
                            TypeName = "Chicken"
                        });
                });

            modelBuilder.Entity("VaxWise.API.Models.Certificate", b =>
                {
                    b.Property<int>("CertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CertId"));

                    b.Property<string>("AuditHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CertId");

                    b.HasIndex("EventId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("VaxWise.API.Models.Farm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FarmId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FarmType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GlnNumber")
                        .HasColumnType("text");

                    b.Property<string>("GpsCoordinates")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FarmId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Farms");
                });

            modelBuilder.Entity("VaxWise.API.Models.FarmWorker", b =>
                {
                    b.Property<int>("FarmWorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FarmWorkerId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("FarmWorkerId");

                    b.HasIndex("FarmId");

                    b.HasIndex("UserId");

                    b.ToTable("FarmWorkers");
                });

            modelBuilder.Entity("VaxWise.API.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HealthRecordId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsUnderTreatment")
                        .HasColumnType("boolean");

                    b.Property<string>("MedicationUsed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WithdrawalDays")
                        .HasColumnType("integer");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("FarmId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("VaxWise.API.Models.LoginAuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LogId");

                    b.HasIndex("AttemptedAt");

                    b.HasIndex("AttemptedAt", "Success");

                    b.ToTable("LoginAuditLogs");
                });

            modelBuilder.Entity("VaxWise.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavcNumber")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PasswordResetToken");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("VaxWise.API.Models.VaccinationEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("integer");

                    b.Property<string>("AuditHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CaptureMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<string>("GpsCoordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SavcNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaccineBatch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.HasIndex("AnimalId");

                    b.HasIndex("FarmId");

                    b.ToTable("VaccinationEvents");
                });

            modelBuilder.Entity("VaxWise.API.Models.VaccineSchedule", b =>
                {
                    b.Property<int>("VaccineScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VaccineScheduleId"));

                    b.Property<int>("AnimalTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNotifiable")
                        .HasColumnType("boolean");

                    b.Property<string>("NotifiableDiseaseName")
                        .HasColumnType("text");

                    b.Property<int>("ReportingWindowHours")
                        .HasColumnType("integer");

                    b.Property<string>("VaccineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VaccineScheduleId");

                    b.HasIndex("AnimalTypeId");

                    b.ToTable("VaccineSchedules");

                    b.HasData(
                        new
                        {
                            VaccineScheduleId = 1,
                            AnimalTypeId = 1,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Foot-and-Mouth Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "FMD Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 2,
                            AnimalTypeId = 1,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Brucellosis",
                            ReportingWindowHours = 24,
                            VaccineName = "Brucellosis Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 3,
                            AnimalTypeId = 1,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Anthrax",
                            ReportingWindowHours = 24,
                            VaccineName = "Anthrax Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 4,
                            AnimalTypeId = 1,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Lumpy Skin Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "Lumpy Skin Disease Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 5,
                            AnimalTypeId = 1,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Bluetongue",
                            ReportingWindowHours = 24,
                            VaccineName = "Bluetongue Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 6,
                            AnimalTypeId = 1,
                            IntervalDays = 365,
                            IsNotifiable = false,
                            ReportingWindowHours = 24,
                            VaccineName = "Blackleg Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 7,
                            AnimalTypeId = 2,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Foot-and-Mouth Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "FMD Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 8,
                            AnimalTypeId = 2,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Anthrax",
                            ReportingWindowHours = 24,
                            VaccineName = "Anthrax Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 9,
                            AnimalTypeId = 2,
                            IntervalDays = 365,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Bluetongue",
                            ReportingWindowHours = 24,
                            VaccineName = "Bluetongue Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 10,
                            AnimalTypeId = 2,
                            IntervalDays = 365,
                            IsNotifiable = false,
                            ReportingWindowHours = 24,
                            VaccineName = "Pasteurellosis Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 11,
                            AnimalTypeId = 3,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Foot-and-Mouth Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "FMD Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 12,
                            AnimalTypeId = 3,
                            IntervalDays = 365,
                            IsNotifiable = false,
                            ReportingWindowHours = 24,
                            VaccineName = "Pasteurellosis Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 13,
                            AnimalTypeId = 4,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Foot-and-Mouth Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "FMD Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 14,
                            AnimalTypeId = 4,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "African Swine Fever",
                            ReportingWindowHours = 24,
                            VaccineName = "African Swine Fever Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 15,
                            AnimalTypeId = 5,
                            IntervalDays = 42,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Newcastle Disease",
                            ReportingWindowHours = 24,
                            VaccineName = "Newcastle Disease Vaccine"
                        },
                        new
                        {
                            VaccineScheduleId = 16,
                            AnimalTypeId = 5,
                            IntervalDays = 180,
                            IsNotifiable = true,
                            NotifiableDiseaseName = "Highly Pathogenic Avian Influenza",
                            ReportingWindowHours = 24,
                            VaccineName = "Avian Influenza Vaccine"
                        });
                });

            modelBuilder.Entity("VaxWise.API.Models.WorkerInvitation", b =>
                {
                    b.Property<int>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvitationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvitationId");

                    b.HasIndex("FarmId");

                    b.HasIndex("InvitedByUserId");

                    b.ToTable("WorkerInvitations");
                });

            modelBuilder.Entity("VaxWise.API.Models.Animal", b =>
                {
                    b.HasOne("VaxWise.API.Models.AnimalType", "AnimalType")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaxWise.API.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnimalType");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("VaxWise.API.Models.Certificate", b =>
                {
                    b.HasOne("VaxWise.API.Models.VaccinationEvent", "VaccinationEvent")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaccinationEvent");
                });

            modelBuilder.Entity("VaxWise.API.Models.Farm", b =>
                {
                    b.HasOne("VaxWise.API.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("VaxWise.API.Models.FarmWorker", b =>
                {
                    b.HasOne("VaxWise.API.Models.Farm", "Farm")
                        .WithMany("Workers")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaxWise.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VaxWise.API.Models.HealthRecord", b =>
                {
                    b.HasOne("VaxWise.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaxWise.API.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("VaxWise.API.Models.VaccinationEvent", b =>
                {
                    b.HasOne("VaxWise.API.Models.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaxWise.API.Models.Farm", null)
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("VaxWise.API.Models.VaccineSchedule", b =>
                {
                    b.HasOne("VaxWise.API.Models.AnimalType", "AnimalType")
                        .WithMany()
                        .HasForeignKey("AnimalTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("VaxWise.API.Models.WorkerInvitation", b =>
                {
                    b.HasOne("VaxWise.API.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaxWise.API.Models.User", "InvitedBy")
                        .WithMany()
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("InvitedBy");
                });

            modelBuilder.Entity("VaxWise.API.Models.AnimalType", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("VaxWise.API.Models.Farm", b =>
                {
                    b.Navigation("Workers");
                });
#pragma warning restore 612, 618
        }
    }
}
